### ISSUE TITLE
dest.on is not a function

### ISSUE THREAD

**Issue by majabee** [filamentgroup/gulpicon#11]
Im using 
"gulp": "^3.9.1",
"glob": "7.1.1",
"gulpicon": "^1.2.1",

when I run my gulpfile I get this error message:

[19:23:55] Starting 'icons'...
[19:23:55] Look, it's a gulpicon!
[19:23:59] Finished 'assemble' after 3.89 s
svg-to-png now spawning phantomjs...
(using path: /Users/xx/yy/sites/projects/gulptest/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs)

/Users/xx/yy/sites/projects/gulptest/node_modules/svg-to-png/node_modules/readable-stream/lib/_stream_readable.js:516
  dest.on('unpipe', onunpipe);
       ^

TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (/Users/xx/yy/sites/projects/gulptest/node_modules/svg-to-png/node_modules/readable-stream/lib/_stream_readable.js:516:8)
    at recurse (/Users/xx/yy/sites/projects/gulptest/node_modules/stream-combiner/index.js:27:16)
    at module.exports (/Users/xx/yy/sites/projects/gulptest/node_modules/stream-combiner/index.js:31:3)
    at Imagemin.run (/Users/xx/yy/sites/projects/gulptest/node_modules/svg-to-png/node_modules/imagemin/index.js:102:13)
    at /Users/xx/yy/sites/projects/gulptest/node_modules/svg-to-png/lib/svg-to-png.js:92:16
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

does someone know how to solve this or what to do?

**Comment by majabee** [comment]
I figured out where the problem start. As soon as I set `compressPNG: true` in my config.js this error occurs.

**Comment by areohbe** [comment]
I am seeing the same error, setting `compressPNG: false` also resolved the issue for me.
