### ISSUE TITLE
 task completion callback called too many times

### ISSUE THREAD

**Issue by olapersson** [filamentgroup/gulpicon#4]
I get an error trying to run gulpicon, `task completion callback called too many times`. Even running on a fresh clone of this repository. 

What could be wrong?

EDIT: checking out the tag v0.1.1 `gulp icons` runs without any error

```
[olapersson@Olas-MBP:~/development/gulpicon on master]
% gulp icons
[16:13:38] Using gulpfile /Users/OlaDev/gulpicon/gulpfile.js
[16:13:38] Starting 'icons'...
[16:13:38] Look, it's a gulpicon!
svg-to-png now spawning phantomjs...
(using path: /Users/OlaDev/gulpicon/node_modules/grunticon-lib/node_modules/svg-to-png/node_modules/phantomjs/lib/phantom/bin/phantomjs)

[16:13:45] Finished 'icons' after 6.89 s
[16:13:45] 'icons' errored after 6.9 s
[16:13:45] Error: task completion callback called too many times
    at finish (/Users/OlaDev/gulpicon/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:15:10)
    at cb (/Users/OlaDev/gulpicon/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at null.<anonymous> (/Users/OlaDev/gulpicon/node_modules/grunticon-lib/lib/grunticon-lib.js:237:6)
    at lib$rsvp$$internal$$tryCatch (/Users/OlaDev/gulpicon/node_modules/grunticon-lib/node_modules/svg-to-png/lib/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/OlaDev/gulpicon/node_modules/grunticon-lib/node_modules/svg-to-png/lib/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/OlaDev/gulpicon/node_modules/grunticon-lib/node_modules/svg-to-png/lib/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/OlaDev/gulpicon/node_modules/grunticon-lib/node_modules/svg-to-png/lib/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
[16:13:45] 'icons' errored after 6.9 s
[16:13:45] Error: task completion callback called too many times
    at finish (/Users/OlaDev/gulpicon/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:15:10)
    at cb (/Users/OlaDev/gulpicon/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at null.<anonymous> (/Users/OlaDev/gulpicon/node_modules/grunticon-lib/lib/grunticon-lib.js:245:5)
    at lib$rsvp$$internal$$tryCatch (/Users/OlaDev/gulpicon/node_modules/grunticon-lib/node_modules/svg-to-png/lib/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/OlaDev/gulpicon/node_modules/grunticon-lib/node_modules/svg-to-png/lib/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/OlaDev/gulpicon/node_modules/grunticon-lib/node_modules/svg-to-png/lib/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/OlaDev/gulpicon/node_modules/grunticon-lib/node_modules/svg-to-png/lib/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)

```

**Comment by Minishlink** [comment]
I have the same issue when running multiple gulpicons in parrallel.

Here is what I would like to do:

``` js
// task shortcut (waiting for a gulpicon with streams)
var gulpiconTask = function(type) {
    var glob = require("glob");
    var files = glob.sync(paths.font[type]);
    var config = {
        dest: path.app + "icons/" + type,
        enhanceSVG: (type === 'interactive'),
        // other configs
    };
    return gulpicon(files, config);
};
gulp.task('icons', ['icons:interactive', 'icons:monochrome']);
gulp.task('icons:monochrome', gulpiconTask('monochrome'));
gulp.task('icons:interactive', gulpiconTask('interactive'));
```

A simple fix is to not make it parrallel:

``` js
gulp.task('icons', ['icons:monochrome']);
gulp.task('icons:monochrome', ['icons:interactive'], gulpiconTask('monochrome'));
gulp.task('icons:interactive', gulpiconTask('interactive'));
```

EDIT: Well I just discovered gulpicon so I now figured out that it is simple nonsense to do that. (it's the data-grunticon-embed attribute that triggers svg inlining)
